version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
    container_name: "chat_app_prod"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    container_name: "db_prod"

  nginx:
    build: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume: