# Generated by Django 4.0 on 2022-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0006_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
