# Generated by Django 4.0 on 2022-12-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0008_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
