# Generated by Django 4.0 on 2022-12-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0010_alter_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
